# Generated by Django 3.1.7 on 2021-03-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210325_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followers',
            new_name='followers_count',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='following',
            new_name='following_count',
        ),
    ]
