# Generated by Django 3.1.7 on 2021-04-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='followers',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='following',
        ),
    ]
